spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://bj-cdb-867r0ta8.sql.tencentcdb.com:60697/dabai-test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: nanquan2021
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

# 配置启动端口
server:
  port: 8080

domain: http://82.156.242.173:8080

http:
  liness:
    host: http://test.liness.cn
    zxMerchantId: EH6J39iWk77N88H6xk1D
    partnerId: JRMF
    zxRasKey: 1fed30e8c07747cc94a9439a62be5f99
    transferCorpId: 28617
    agreementType: 28617
  huanong:
    host: https://hermes-apollo.chinahuanong.com.cn
    appid: MINI_DB
    appkey: 0741978a1f7aa842
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCWp8Kk+iu61XRP/TB/41KbD/R/RVrenXEX7GUAuf2f0CTa1zfIKYveoINMHC6WWJzOmkMLwHZxXe+mufJAUb5P3SjfOLcqbrnYlVajd8gFXiGyJSX94WlG7v9tfQAwFAAdV0LxstHjFKj8hu40CSj/7pk0o0Vmqj0plJy1wCN8tQIDAQAB
    privateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJanwqT6K7rVdE/9MH/jUpsP9H9FWt6dcRfsZQC5/Z/QJNrXN8gpi96gg0wcLpZYnM6aQwvAdnFd76a58kBRvk/dKN84typuudiVVqN3yAVeIbIlJf3haUbu/219ADAUAB1XQvGy0eMUqPyG7jQJKP/umTSjRWaqPSmUnLXAI3y1AgMBAAECgYBQwGscctutsWw+07+DTR2h79NlxI8Ic+uCnzskQI0pdC/M/T7xExPdqLu3uANgou6p7xWw3uCds3QZMeIfh7Ex2IzXVBNh/0xxQZYkVO4dpB1dB8H2T8f6eQAOTDYgd2vS2gU7vmccSoOxNQXBWATi1RstloGY+GTVyn1tsRTeoQJBAOVrokBQMxKgw0Toi5NrifXl6X3luiqlEmVCC2b0gJRuYlgvs9/47asx3T6xEp2BXEiJbnsGeSqc98SsHhTzFfMCQQCoHAleAE/mSGtwcRT0YE+qREmT9fHYtcnXB1BjyXrP4HqH9ygb760qRF+GVkUs4KMNGBdqqBtPBMbzic5snQS3AkEAhlGoIwNRg5x/9v43ic4ybbd4Ju+zOXh/9qzeRB7ukPi3t23mYEE71TlSkXvWrESqpQVhm8HEewB/x7QFwLo5pQJAJ1vpFYkdK91oyjqvnUevXz39vBapOQPW7fFYcQSLLIByL8M+MMw8ztiTRPCN4aP2iOpLET2qpyWHLx3kpqlcoQJALTRaF70e+KPdongbGz6jQRfpUcSjXVfTMHQFsie15gyJCHcbihndj5Ay5gFlQszxWvv3aRmlax/IKfuJWik2LA==

tencentcloud:
  secretId: AKIDBD0Zu0rTqyrUt64mFTRAeuvhEVXKsCI8
  secretKey: d0B6mCNJ0RdbLq79wUotkLhohMmxud7N
  submitCodeTemplateId: 1417815
#  loginTemplateId: 1040125
#  registerTemplateId: 1040122
#  rePasswordTemplateId: 1049348
  notifyTemplateId: 1066246
  sdkAppId: 1400685449
  signName: 众信健康

wx:
  miniapp:
    configs:
      - appid: wx423e3a2bd9fb9ecb
        secret: dad65c199e50a94658981568c1cbc5af
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON





