spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://bj-cdb-867r0ta8.sql.tencentcdb.com:60697/dabai-test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: nanquan2021
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

# 配置启动端口
server:
  port: 8080

http:
  liness:
    host: http://test.liness.cn
    merchantId: 70a8084bcF1Cu8r02K85
    partnerId: JRMF
    rasKey: 12898884523b4dbab41114267ddb72d1
    transferCorpId: 28617
    agreementType: 28617
  huanong:
    host: https://hermes-apollo.chinahuanong.com.cn
    appid: MINI_DB
    appkey: 0741978a1f7aa842

wx:
  miniapp:
    configs:
      - appid: #微信小程序的appid
        secret: #微信小程序的Secret
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON





