spring:
  messages:
    encoding: UTF-8
  #环境
  profiles:
    active: test
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#    default-property-inclusion: non_null
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

# 配置启动端口
server:
  tomcat:
    additional-tld-skip-patterns: jaxb1-impl.jar,jsr173_1.0_api.jar,jaxb-api.jar,activation.jar
  servlet:
    context-path: /dabai

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

mapper:
  identity: MYSQL

#日志配置
logging:
  config: classpath:logback-spring.xml

#佣金计算比例
commission:
  radio: 0.1



