spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://ip:port/*?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

# 配置启动端口
server:
  port: 8080

tencentcloud:
  secretId: AKIDSny1wgEgJrDaorlV6WkmeLSNFya4UtCK
  secretKey: 2sW0Rn13reEbliSyGKCqKfniQuABxVpv
  submitCodeTemplateId: 1040127
  loginTemplateId: 1040125
  registerTemplateId: 1040122
  rePasswordTemplateId: 1049348
  notifyTemplateId: 1066246
  sdkAppId: 1400548038
  signName: 大白科技

wx:
  miniapp:
    configs:
      - appid: wxeeff2ac6fe1b54bc
        secret: cde90612edd0fbe17b4fa9368ba6b04e
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON





